### ISSUE TITLE
Using the skill and saving throw macros causes and error

### ISSUE THREAD

**Issue by Pjb518** [UnicornHeartClub/Issues#57]
Skills and saving throws have individual clickable links which execute a macro. Currently clicking the link causes the following error message to appear.

`Error: Problem while executing macro.`

**Comment by Pjb518** [comment]
Console error message:

````game.js:3 abort("trap!") at Error
    at jsStackTrace (https://beta.poweredvtt.com/_next/2dde75d4-e6e1-4bf6-a0b7-afa2804c010f/page/app/play/game.js:3:2529445)
    at stackTrace (https://beta.poweredvtt.com/_next/2dde75d4-e6e1-4bf6-a0b7-afa2804c010f/page/app/play/game.js:3:2529605)
    at abort (https://beta.poweredvtt.com/_next/2dde75d4-e6e1-4bf6-a0b7-afa2804c010f/page/app/play/game.js:3:2549225)
    at _llvm_trap (https://beta.poweredvtt.com/_next/2dde75d4-e6e1-4bf6-a0b7-afa2804c010f/page/app/play/game.js:3:2539959)
    at wasm-function[400]:213
    at wasm-function[399]:72
    at wasm-function[398]:145
    at wasm-function[526]:76
    at wasm-function[558]:110
    at wasm-function[561]:133````
